---
refresh_interval: 600 # seconds
max_price: 1750 # dollars
urls:
  - https://www.pokemoncenter.com/product/146-10899/pokemon-tcg-xy-furious-fists-sleeved-booster-pack-10-cards
  - https://www.pokemoncenter.com/product/699-16624/pokemon-tcg-xy-furious-fists-dark-hammer-theme-deck
  - https://www.pokemoncenter.com/product/699-16626/pokemon-tcg-xy-furious-fists-3-booster-packs-coin-and-slurpuff-promo-card
  - https://www.pokemoncenter.com/product/290-80748/pokemon-tcg-alakazam-v-box
  - https://www.pokemoncenter.com/product/290-80333/pokemon-tcg-shining-legends-super-premium-collection
  - https://www.pokemoncenter.com/product/175-80768/pokemon-tcg-sword-and-shield-vivid-voltage-elite-trainer-box
  - https://www.pokemoncenter.com/product/290-80545/pokemon-tcg-champion-s-path-elite-trainer-box
  - https://www.pokemoncenter.com/product/290-80319/pokemon-tcg-shining-legends-elite-trainer-box
  - https://www.pokemoncenter.com/product/716-88222/nintendo-switch-joy-con-neon-purple-neon-orange
  - https://www.pokemoncenter.com/product/716-88221/nintendo-switch-joy-con-blue-neon-yellow
  - https://www.pokemoncenter.com/product/716-88217/nintendo-switch-with-neon-blue-and-neon-red-joy-con
  - https://www.pokemoncenter.com/product/716-88226/nintendo-switch-lite-turquoise
  - https://www.pokemoncenter.com/product/716-88266/nintendo-switch-lite-coral
  - https://www.pokemoncenter.com/product/716-88228/nintendo-switch-lite-gray
  - https://www.pokemoncenter.com/product/716-88230/nintendo-switch-lite-yellow
  - https://www.pokemoncenter.com/product/716-52782/pokemon-sword
...
